access:
  url: https://app.quotemedia.com/datatool/getSnapQuotes.json
  headers:
    Origin: https://web.tmxmoney.com
server:
  port: 4000
help:
  message:
    test: App is running well!
    default: Usage - /quote?symbol=xxx&token=xxx 

  